#!/usr/bin/env ruby
$LOAD_PATH << 'lib'

require 'redis_client_factory'
require 'redis_subscriber'
require 'stdout_handler'
require 'metadata_aggregator'
require 'request_rate_logger'

$stdout.sync = true
trap(:INT) { exit }

app_environment_id = JSON.parse(ENV.fetch('VCAP_APPLICATION')).fetch('space_id')
app_instance_id = ENV.fetch('CF_INSTANCE_INDEX')

redis = RedisClientFactory.create('async-redis')

stdout_handler = StdoutHandler.new
metadata_aggregator = MetadataAggregator.new(redis, app_environment_id: app_environment_id)
request_rate_logger = RequestRateLogger.new(
    redis,
    app_environment_id: app_environment_id,
    app_instance_id: app_instance_id
)

subscriber = RedisSubscriber.new(redis)
subscriber.subscribe('requestMetadata', stdout_handler)
subscriber.subscribe('requestMetadata', metadata_aggregator)
subscriber.subscribe('requestMetadata', request_rate_logger)
subscriber.join